//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCstok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_MUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MUSTERILER()
        {
            this.TBL_SATISLAR = new HashSet<TBL_SATISLAR>();
        }
        [DisplayName("Müþteri ID")]
        public int MUSTERIID { get; set; }
        [DisplayName("Müþteri Ad")]
        [Required(ErrorMessage ="Bu alan boþ býrakýlamaz")]
        [StringLength(40,ErrorMessage ="En fazla 40 karakter girebilirsiniz")]
        public string MUSTERIAD { get; set; }
        [DisplayName("Müþteri Soyad")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        [StringLength(40, ErrorMessage = "En fazla 40 karakter girebilirsiniz")]
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATISLAR> TBL_SATISLAR { get; set; }
    }
}
